    .align 2
voicegroup199::
	voice_keysplit voicegroup005, KeySplitTable1 // piano
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 255, 254, 0, 255 // bright acoustic
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // electric grand
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // honky tonk
	voice_keysplit voicegroup198, KeySplitTable1 // EP1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // EP2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // harpsichord
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // clavinet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // celesta
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 235 // glockenspiel
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // music box
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_vibraphone_60, 255, 165, 231, 249 // vibraphone
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_marimba, 255, 165, 231, 249 // marimba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // xylophone
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // tubular bells
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // dulcimer
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // drawbar organ
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 210 // percussive organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // rock organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // church organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // reed organ
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165 // accordion
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // harmonica
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // tango accordion
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 76 // nylon guitar
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_steel_str_guitar, 255, 249, 25, 76 // steel guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // jazz guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // clean electric guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // muted electric guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127 // overdrive guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127 // dist. guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // guitar harmonics
	voice_keysplit voicegroup193, KeySplitTable8 // acoustic bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 250, 0, 149 // fingered electric bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // picked electric bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // fretless bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // slap bass 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // slap bass 2
	voice_directsound 60, 0, DirectSoundWaveData_route_22_bass, 255, 250, 0, 149 // synth bass 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // synth bass 2
	voice_keysplit voicegroup192, KeySplitTable6 // violin
	voice_keysplit voicegroup196, KeySplitTable6 // viola
	voice_keysplit voicegroup194, KeySplitTable7 // cello
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // contrabass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // trem. strings
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165 // pizz. strings
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 204 // harp
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226 // timpani
	voice_keysplit voicegroup006, KeySplitTable2 // fast strings
	voice_keysplit voicegroup006, KeySplitTable2 // slow strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // synth strings 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // synth strings 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // choir aahs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // choir oohs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // synth voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // orchestra hit
	voice_keysplit voicegroup007, KeySplitTable3 // trumpet
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trombone, 255, 0, 193, 127 // trombone
	voice_keysplit voicegroup008, KeySplitTable4 // tuba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // muted trumpet
	voice_keysplit voicegroup009, KeySplitTable5 // french horn
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // brass section
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // synth brass 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // synth brass 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // soprano sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // alto sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // tenor sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // bari sax
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 255, 165, 154, 127 // oboe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // english horn
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bassoon, 255, 127, 231, 127 // bassoon
	voice_keysplit voicegroup195, KeySplitTable3 // clarinet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // piccolo
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127 // flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // recorder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // pan flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // blown bottle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // shakuhachi
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // whistle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // ocarina
	voice_directsound 60, 0, DirectSoundWaveData_route_22_sine, 255, 0, 255, 13 // square lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // saw lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // calliope lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // chiffer lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // charang
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // vox lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // fifth saw lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // bass + lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // new age pad
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // warm pad
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // polysynth
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // choir pad
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // bowed glass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // metallic pad
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // halo pad
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // sweep pad
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // ice rain
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // soundtrack
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // crystal
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // atmosphere
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // brightness
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // goblins
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // echoes
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // sci-fi
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // sitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // banjo
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // shamisen
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // koto
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // kalimba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // bagpipe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // fiddle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // shanai
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // tinkle bell
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // agogo
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // steel drums
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // woodblock
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // taiko drum
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // melodic tom
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // synth drum
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // reverse cymbal
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // guitar fret noise
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // breath
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // seashore
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // bird tweet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // telephone ring
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // helicopter
	voice_keysplit_all voicegroup002 // drums
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 // gunshot
